# NOTE: update this with your service name
service: backend-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  # Defines an HTTP API endpoint that calls the main function in address/get.js
  # - path: url path is /address/{postalCode}/{houseNumber}
  # - method: GET request
  addressGet:
    handler: address/get.main
    events:
      - http:
          path: address/{postalCode}/{houseNumber}
          method: get

  # Defines an HTTP API endpoint that calls the main function in company/get.js
  # - path: url path is /company
  # - method: GET request
  companyGet:
    handler: company/get.main
    events:
      - http:
          path: company
          method: get

  # Defines an HTTP API endpoint that calls the main function in company/create.js
  # - path: url path is /company
  # - method: POST request
  companyCreate:
    handler: company/create.main
    events:
      - http:
          path: company
          method: post
